#!/usr/bin/env bash

# Prerequisites:
apts=(
  python2.7
  software-properties-common
  apt-transport-https
  ca-certificates
)
apt-get update
apt-get install -y ${apts[@]}

# For tmate:
add-apt-repository ppa:nviennot/tmate

# For docker:
sudo apt-key adv \
  --keyserver hkp://p80.pool.sks-keyservers.net:80 \
  --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' \
  > /etc/apt/sources.list.d/docker.list

apts=(
  aptitude
  build-essential
  cpanminus
  curl
  docker-engine
  exuberant-ctags
  fontconfig
  git
  gist
  htop
  language-pack-en
  libssl-dev
  libtool
  man-db
  manpages
  mosh
  perl-doc
  python-virtualenv
  python2.7-dev
  silversearcher-ag
  tig
  tmate
  tmux
  tree
  vim
  weechat
  wget
)

apt-get update
apt-get install -y ${apts[@]}
