#!/usr/bin/env bash

cd $HOME

hostname "pairup-$PAIRUP_HOST_USER"

(
  set -x
  if [[ ! -d .ssh ]]; then
    mkdir -p .ssh
    chmod 0600 .ssh
  fi
  ssh-keyscan github.com >> .ssh/known_hosts

  [[ -d src/git-hub ]] ||
    git clone git@github.com:ingydotnet/git-hub src/git-hub

  cat /bashrc >> .bashrc
  if [[ -e ./.../conf ]]; then
    .../bin/... install
    mkdir -p .sh
    cp /bashrc .sh/local
  fi
  if [[ -h .ssh/config ]]; then
    link="$(readlink .ssh/config)"
    unlink .ssh/config
    cp "$link" .ssh/config
    chmod -R go-rwx ~/.ssh
  fi
) |& tee /pairup.log

docker daemon &> /docker-daemon.log &

touch /NEW

tmate
